version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: always
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs:rw
            - ./htpasswd:/etc/nginx/htpasswd
        ports:
            - "80:80"
            - "443:443"
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
