version: '2'
services:
    nginx:
        image: fholzer/nginx-brotli:v1.10.2
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./certs:/etc/nginx/certs:rw
            - ./htpasswd:/etc/nginx/htpasswd
            - ./vhost.d:/etc/nginx/vhost.d
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
        networks:
            - default
            - nginx-proxy

    dockergen:
        image: jwilder/docker-gen
        container_name: docker-gen
        restart: always
        command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
        networks:
            - nginx-proxy

    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt-nginx-proxy-companion
        restart: always
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/etc/nginx/certs:rw
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
